### ISSUE TITLE
failed to start background process

### ISSUE THREAD

**Issue by jwijffels** [cyverse/irodsfs#11]
hello again, I've got this type of setup

```
cat > ~/.irods/irods_environment.json <<'EOF'
{
  "irods_host": "irods.test.be",
  "irods_port": 1247,
  "irods_zone_name": "zoneabc",
  "irods_authentication_scheme": "PAM",
  "irods_encryption_algorithm": "AES-256-CBC",
  "irods_encryption_salt_size": 8,
  "irods_encryption_key_size": 32,
  "irods_encryption_num_hash_rounds": 16,
  "irods_user_name": "user1234",
  "irods_ssl_ca_certificate_file": "",
  "irods_ssl_verify_server": "cert",
  "irods_client_server_negotiation": "request_server_negotiation",
  "irods_client_server_policy": "CS_NEG_REQUIRE",
  "irods_default_resource": "default"
}
EOF
```

which gives met the following paths on irods

```
ubuntu@test:~/irodsfs$ ils
/zoneabc/home/user1234:
  C- /zoneabc/home/user1234/getuigenissen-acc
  C- /zoneabc/home/user1234/getuigenissen-dev
  C- /zoneabc/home/user1234/test
```

When setting up the configuration of irodsfs

```
cat > ~/.irods/config.yaml <<'EOF'
host: irods.test.be
port: 1247
proxy_user: user1234
client_user: user1234
zone: zoneabc
password: 

authscheme: pam
ssl_ca_cert_file: "/etc/ssl/certs/ca-certificates.crt"
ssl_verify_server: "cert"
ssl_encryption_key_size: 32
ssl_encryption_algorithm: "AES-256-CBC"
ssl_encryption_salt_size: 8
ssl_encryption_hash_rounds: 16

path_mappings:
  - irods_path: /zoneabc/home/user1234/getuigenissen-acc
    mapping_path: /
    resource_type: dir
EOF
```

I'm getting `failed to start background process` 

```
ubuntu@test:~/irodsfs$ ./bin/irodsfs -config ~/.irods/config.yaml /home/ubuntu/irods
time="2022-02-10T10:09:22+01:00" level=info msg="Logging to /tmp/irodsfs_c82dcgnk61svmeli9rb0.log" function=processArguments package=main
time="2022-02-10T10:09:22+01:00" level=info msg="Found FUSE Device. Starting iRODS FUSE Lite." function=parentMain package=main
time="2022-02-10T10:09:22+01:00" level=info msg="Running the process in the background mode" function=parentRun package=main
time="2022-02-10T10:09:22+01:00" level=info msg="Process id = 211130" function=parentRun package=main
time="2022-02-10T10:09:22+01:00" level=info msg="Sending configuration data" function=parentRun package=main
time="2022-02-10T10:09:22+01:00" level=info msg="Successfully sent configuration data to background process" function=parentRun package=main
time="2022-02-10T10:09:22+01:00" level=error msg="failed to start background process" function=parentRun package=main
time="2022-02-10T10:09:22+01:00" level=error msg="failed to run the foreground process" error="failed to start background process" function=parentMain package=main
time="2022-02-10T10:09:22+01:00" level=fatal msg="failed to start background process" function=parentMain package=main
```

Can you explain how to map the following to irodsfs equivalents. I see in https://github.com/cyverse/irodsfs/blob/032cdc9d842dcb55e076d6ef8b36638e182f3fde/examples/ssl_account_file.yml that there used to be variants of these for CS_NEG_REQUIRE/cs_negotiation but couldn't find it in the docs.
Also what needs to be in irods_ssl_ca_certificate_file. For me currently this is the default ssl certificate file on my Ubuntu machine.

```
  "irods_ssl_ca_certificate_file": "",
  "irods_ssl_verify_server": "cert",
  "irods_client_server_negotiation": "request_server_negotiation",
  "irods_client_server_policy": "CS_NEG_REQUIRE",
  "irods_default_resource": "default"
```

thanks for the help!

**Comment by iychoi** [comment]
Sorry for late response. I am currently out of office. Will be back in next couple of days. Will check this when I am back!

**Comment by iychoi** [comment]
Here's example SSL Config.
https://github.com/cyverse/irodsfs/blob/main/examples/ssl_config.yml

Here's the equivalents. 
```
host: irods.test.be
port: 1247
proxy_user: user1234
client_user: user1234
zone: zoneabc
password: 

auth_scheme: pam
ssl_ca_cert_file: "/etc/ssl/certs/ca-certificates.crt"
ssl_verify_server: "cert"
ssl_encryption_key_size: 32
ssl_encryption_algorithm: "AES-256-CBC"
ssl_encryption_salt_size: 8
ssl_encryption_hash_rounds: 16

path_mappings:
  - irods_path: /zoneabc/home/user1234/getuigenissen-acc
    mapping_path: /
    resource_type: dir
```

The only mistake in your config file for irodsfs is "authscheme" field. The field name should be "auth_scheme".
Let me know if you have further questions or errors.

Illyoung Choi
